Fixed the NoSuchMethodError ...about the missing static interface sendPackageBroadcast for the PackageManagerService.java by overloading the interface